branches:
  only:
  - master
language: go
go: 1.20.x
dist: bionic
install:
  - go get -t -v ./...
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
  - pyenv global 3.8
  - pip install --user mkdocs-material
script:
  - make lint
  - make build
  - make docs
  - make test
